main() {
  try {
    print(1);
  } on Exception<caret> catch (e) {
    // TODO
  }
}